/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef xtrace_CONSTANTS_H
#define xtrace_CONSTANTS_H

#include "xtrace_types.h"

namespace xtrace {

class xtraceConstants {
 public:
  xtraceConstants();

};

extern const xtraceConstants g_xtrace_constants;

} // namespace

#endif
