/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "xtrace_constants.h"

namespace xtrace {

const xtraceConstants g_xtrace_constants;

xtraceConstants::xtraceConstants() {
}

} // namespace

